version: '3.8'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

  front:
    build:
      dockerfile: Dockerfile
      context: ./aionapp
    ports:
      - "${NODE_PORT}:3000"
    volumes:
      - ./src/app:/app
      - /aionapp/node_modules
    working_dir: /app
    environment:
      - API_URL=http://api:8000
    command: npm run dev
    stdin_open: true
    tty: true

  api:
    build: 
      dockerfile: Dockerfile
      context: ./aionapi
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "${API_PORT}:8000"
    volumes:
      - ./src/app/api:/api
    working_dir: /api
    stdin_open: true
    environment:
      - DJANGO_DEBUG=False
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
    depends_on:
      - db

volumes:
  postgres_data:
  pgadmin_data:
