# Generated by Django 5.0.7 on 2024-08-07 16:46

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_last_login_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(max_length=255, validators=[api.models.validate_fullname]),
        ),
    ]
